AWSTemplateFormatVersion: '2010-09-09'
Description: Example CloudFormation template
Parameters:
  Env:
    Type: String
Resources:
  ExampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub example-bucket-${Env}
