name: ci

on:
  push:
    branches: [ main ]
    paths:
      - 'automation-framework/**'
      - 'cloud-native-app/**'
      - 'ai-test-generation/**'
      - '.github/workflows/**'
      - 'Makefile'
  pull_request:
    paths:
      - 'automation-framework/**'
      - 'cloud-native-app/**'
      - 'ai-test-generation/**'
      - '.github/workflows/**'
      - 'Makefile'

jobs:
  automation-framework:
    name: Automation Framework (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: automation-framework
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e ".[test]"; fi
          # Install Allure dependencies
          pip install allure-pytest allure-python-commons
      - run: |
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi
          if command -v black >/dev/null 2>&1; then black --check . || true; fi
      - name: Run Tests with Allure Results
        if: always()
        run: |
          # Create reports directory
          mkdir -p reports/allure-results
          
          # Check if tests directory exists
          if [ -d tests ]; then
            echo "Found tests directory, running pytest..."
            pytest tests/ --alluredir=reports/allure-results -v || true
          else
            echo "No tests directory found"
          fi
          
          # Check for test files in current directory
          if ls test_*.py 1> /dev/null 2>&1; then
            echo "Found test files in current directory, running pytest..."
            pytest test_*.py --alluredir=reports/allure-results -v || true
          fi
          
          # List generated files for debugging
          echo "Allure results directory contents:"
          ls -la reports/allure-results/ || echo "No Allure results generated"
      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "reports/allure-results" ] && [ "$(ls -A reports/allure-results)" ]; then
            echo "Installing Allure commandline..."
            npm install -g allure-commandline
            echo "Generating Allure report for automation-framework..."
            allure generate reports/allure-results --clean -o reports/allure-report
            echo "Allure report generated successfully"
          else
            echo "No Allure results found for automation-framework"
          fi

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-framework-allure-results
          path: reports/allure-results/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-framework-allure-report
          path: reports/allure-report/
          retention-days: 30

  ai-test-generation:
    name: AI Test Generation (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-test-generation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
          # Install Allure dependencies
          pip install allure-pytest allure-python-commons
      - run: |
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi
          if command -v black >/dev/null 2>&1; then black --check . || true; fi
      - name: Run Tests with Allure Results
        if: always()
        run: |
          # Create reports directory
          mkdir -p reports/allure-results
          
          # Check if tests directory exists
          if [ -d tests ]; then
            echo "Found tests directory, running pytest..."
            pytest tests/ --alluredir=reports/allure-results -v || true
          else
            echo "No tests directory found"
          fi
          
          # Check for test files in current directory
          if ls test_*.py 1> /dev/null 2>&1; then
            echo "Found test files in current directory, running pytest..."
            pytest test_*.py --alluredir=reports/allure-results -v || true
          fi
          
          # List generated files for debugging
          echo "Allure results directory contents:"
          ls -la reports/allure-results/ || echo "No Allure results generated"
      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "reports/allure-results" ] && [ "$(ls -A reports/allure-results)" ]; then
            echo "Installing Allure commandline..."
            npm install -g allure-commandline
            echo "Generating Allure report for ai-test-generation..."
            allure generate reports/allure-results --clean -o reports/allure-report
            echo "Allure report generated successfully"
          else
            echo "No Allure results found for ai-test-generation"
          fi

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-test-generation-allure-results
          path: reports/allure-results/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-test-generation-allure-report
          path: reports/allure-report/
          retention-days: 30

  cloud-native-app:
    name: Cloud Native App (TypeScript/Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cloud-native-app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          # Install Node.js dependencies
          if [ -f package.json ]; then yarn install; fi
          # Install Python dependencies for regression tests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest allure-pytest allure-python-commons
      - run: |
          if command -v yarn >/dev/null 2>&1; then yarn lint || true; fi
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi
      - name: Run Tests with Allure Results
        if: always()
        run: |
          # Create reports directory
          mkdir -p reports/allure-results
          
          # Check if tests directory exists
          if [ -d tests ]; then
            echo "Found tests directory, running pytest..."
            pytest tests/ --alluredir=reports/allure-results -v || true
          else
            echo "No tests directory found"
          fi
          
          # Check for test files in current directory
          if ls test_*.py 1> /dev/null 2>&1; then
            echo "Found test files in current directory, running pytest..."
            pytest test_*.py --alluredir=reports/allure-results -v || true
          fi
          
          # Run TypeScript/Jest tests (without Allure for now)
          if [ -f package.json ] && command -v yarn >/dev/null 2>&1; then
            echo "Running TypeScript/Jest tests..."
            yarn test --coverage || true
          fi
          
          # List generated files for debugging
          echo "Allure results directory contents:"
          ls -la reports/allure-results/ || echo "No Allure results generated"
      - name: Generate Allure Report
        if: always()
        run: |
          if [ -d "reports/allure-results" ] && [ "$(ls -A reports/allure-results)" ]; then
            echo "Installing Allure commandline..."
            npm install -g allure-commandline
            echo "Generating Allure report for cloud-native-app..."
            allure generate reports/allure-results --clean -o reports/allure-report
            echo "Allure report generated successfully"
          else
            echo "No Allure results found for cloud-native-app"
          fi

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cloud-native-app-allure-results
          path: reports/allure-results/
          retention-days: 30

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cloud-native-app-allure-report
          path: reports/allure-report/
          retention-days: 30

