name: ci

on:
  push:
    branches: [ main ]
    paths:
      - 'automation-framework/**'
      - 'cloud-native-app/**'
      - 'ai-test-generation/**'
      - '.github/workflows/**'
      - 'Makefile'
  pull_request:
    paths:
      - 'automation-framework/**'
      - 'cloud-native-app/**'
      - 'ai-test-generation/**'
      - '.github/workflows/**'
      - 'Makefile'

jobs:
  automation-framework:
    name: Automation Framework (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: automation-framework
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            automation-framework/requirements.txt
            automation-framework/pyproject.toml
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi
      - run: |
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi
          if command -v black >/dev/null 2>&1; then black --check . || true; fi
      - run: |
          if [ -d tests ] || ls -1 *.py >/dev/null 2>&1; then pytest -q || true; else echo 'no tests'; fi

  ai-test-generation:
    name: AI Test Generation (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-test-generation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            ai-test-generation/requirements.txt
            ai-test-generation/pyproject.toml
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi
      - run: |
          if command -v ruff >/dev/null 2>&1; then ruff check . || true; fi
          if command -v black >/dev/null 2>&1; then black --check . || true; fi
      - run: |
          if [ -d tests ] || ls -1 *.py >/dev/null 2>&1; then pytest -q || true; else echo 'no tests'; fi

  cloud-native-app:
    name: Cloud Native App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "Add CDK or infra steps when ready"
