name: Process Allure Reports

on:
  workflow_call:
    inputs:
      module:
        type: string
        required: true
        default: all
        description: Module to process Allure report for
  workflow_dispatch:
    inputs:
      module:
        type: choice
        options:
          - automation-framework
          - ai-rulesets
          - cloud-native-app
          - react-playwright-demo
          - all
        required: true
        default: all
        description: Module to process Allure report for

jobs:
  process-allure-reports:
    name: Process Allure Reports
    runs-on: ubuntu-latest
    if: always()
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Download Allure Reports
        uses: actions/download-artifact@v4
        with:
          pattern: "*-allure-report"
          path: allure-reports/
          merge-multiple: true
        continue-on-error: true
          
      - name: Debug Downloaded Allure Artifacts
        run: |
          echo "=== Allure Reports Debug ==="
          if [ -d "allure-reports" ]; then
            echo "Allure reports directory exists"
            ls -la allure-reports/
            echo "Subdirectories:"
            find allure-reports/ -type d -maxdepth 2
            echo "Files:"
            find allure-reports/ -type f | head -20
          else
            echo "No allure-reports directory found"
          fi
          
      - name: Setup Python for Allure processing
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Process Allure Reports
        run: |
          echo "=== Processing Allure Reports ==="
          
          # Create processed reports directory
          mkdir -p processed-allure-reports
          
          # Process each module's Allure report
          for module in automation-framework ai-rulesets cloud-native-app react-playwright-demo; do
            echo "Processing $module Allure report..."
            
            if [ -d "allure-reports/${module}-allure-report" ]; then
              echo "Found ${module} Allure report"
              
              # Handle different artifact structures
              if [ -d "allure-reports/${module}-allure-report/${module}/reports/allure-report" ]; then
                echo "Using nested structure: ${module}/reports/allure-report"
                cp -r "allure-reports/${module}-allure-report/${module}/reports/allure-report" "processed-allure-reports/${module}"
              elif [ -d "allure-reports/${module}-allure-report/reports/allure-report" ]; then
                echo "Using reports structure: reports/allure-report"
                cp -r "allure-reports/${module}-allure-report/reports/allure-report" "processed-allure-reports/${module}"
              else
                echo "Using direct structure: artifact contents"
                # Copy all files from the artifact
                find "allure-reports/${module}-allure-report" -name "*.html" -exec cp {} "processed-allure-reports/${module}/" \;
                find "allure-reports/${module}-allure-report" -name "*.css" -exec cp {} "processed-allure-reports/${module}/" \;
                find "allure-reports/${module}-allure-report" -name "*.js" -exec cp {} "processed-allure-reports/${module}/" \;
                find "allure-reports/${module}-allure-report" -name "data" -type d -exec cp -r {} "processed-allure-reports/${module}/" \;
                find "allure-reports/${module}-allure-report" -name "widgets" -type d -exec cp -r {} "processed-allure-reports/${module}/" \;
              fi
              
              echo "Processed ${module} report successfully"
              ls -la "processed-allure-reports/${module}/"
            else
              echo "No Allure report found for ${module}"
            fi
          done
          
          echo "=== Final Processed Reports ==="
          ls -la processed-allure-reports/

      - name: Upload Processed Allure Reports
        uses: actions/upload-artifact@v4
        with:
          name: processed-allure-reports
          path: processed-allure-reports/
          retention-days: 30
