name: Code Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      check_type:
        description: 'Type of quality check to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - readmes
        - workflows
        - tests
        - versions
        - fix

jobs:
  quality-check:
    runs-on: ubuntu-latest
    name: Code Quality Validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the ai-rulesets package which contains the quality checker
        pip install -e ai-rulesets/
        # Install any additional dependencies if needed
        pip install -r scripts/requirements.txt || echo "No requirements.txt found in scripts/"
        
    - name: Run quality checks
      run: |
        case "${{ github.event.inputs.check_type || 'all' }}" in
          "all")
            quality-check
            ;;
          "readmes")
            quality-check --readmes-only
            ;;
          "workflows")
            quality-check --workflows-only
            ;;
          "tests")
            quality-check --tests-only
            ;;
          "versions")
            quality-check --versions-only
            ;;
          "fix")
            quality-check --fix
            ;;
        esac
        
    - name: Export results
      if: always()
      run: |
        quality-check --export quality-results.json
        
    - name: Upload quality results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: quality-check-results
        path: quality-results.json
        retention-days: 30
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          try {
            const results = JSON.parse(fs.readFileSync('quality-results.json', 'utf8'));
            const summary = results.summary || {};
            const totalIssues = summary.total || 0;
            const errors = summary.errors || 0;
            const warnings = summary.warnings || 0;
            
            const comment = `## 🔍 Code Quality Check Results
            
            **Summary:**
            - Total Issues: ${totalIssues}
            - Errors: ${errors}
            - Warnings: ${warnings}
            
            ${totalIssues === 0 ? '✅ No quality issues found!' : '⚠️ Quality issues detected. Please review the details below.'}
            
            <details>
            <summary>View detailed results</summary>
            
            \`\`\`json
            ${JSON.stringify(results, null, 2)}
            \`\`\`
            </details>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } catch (error) {
            console.log('Could not parse quality results:', error);
          }
